### ISSUE TITLE
Migrer ce repo vers novafloss

### ISSUE THREAD

**Issue by aRkadeFR** [novafloss/check_po#6]
check_po est actuellement sur pypi:
https://pypi.python.org/pypi/check_po/0.6

Il faut liberer ce code et le mettre sur novafloss.

Je veux bien me mettre mainteneur de ce repo.

**Comment by aRkadeFR** [comment]
Merci @zebuline

**Comment by Natim** [comment]
Quel est ton login pypi?

**Comment by Natim** [comment]
J ai mis aRkadeFR en mainteneur

**Comment by aRkadeFR** [comment]
Merci @Natim
